image: python:3.7

before_script:
  - pip install tox setuptools qualifier
cache:
  paths:
  - /root/.cache
stages:
  - qualifier
  - style
  - test
  - package

qualifier:
  stage: qualifier
  script:
    - update_qualifier --no-use-git --branch-name "$CI_COMMIT_REF_NAME" --tag-name "$CI_COMMIT_TAG"

py37:
  stage: test
  script:
    - tox -e py37

flake8:
  stage: style
  script:
    - tox -e flake8

wheel:
  stage: package
  script:
    tox -e wheel
  artifacts:
    paths:
      - dist/

sdist:
  stage: package
  script:
    tox -e sdist
  artifacts:
    paths:
      - dist/
